### ISSUE TITLE
/time command should not accept 'invalid' input

### ISSUE THREAD

**Issue by CharleneHoogkamer** [SVredeveld/mariobot#15]
The /time command accepts all kinds of 'invalid' inputs, such as '1' or 'aaaa'.
These inputs are inserted at the bottom of the leaderboard.

The expected input for the /time command should have this format: 00:30:22. 
Another requirement should be that you can only update your time if it is faster than your previous time.

**Comment by WoJoVo** [comment]
I have a fix for validating and formatting time ready. Could I have this issue?

Not sure if only accepting faster times is desired, for example in the case if somebody makes a typo and wants to adjust their time to a lower one retroactively.
