### ISSUE TITLE
Add previous and new leaderboard place in time command

### ISSUE THREAD

**Issue by SVredeveld** [SVredeveld/mariobot#7]
When a user adds a new time, the /time command only returns the following text;
`Time score updated for [@user] with a time of [X:XX:XXX]`

It would be nice if the command also returns the previous and new placement from this user. 

`Time score updated for [@user] with a time of [X:XX:XXX]. They went from [previous place] to [current place]`

**Comment by GrillSkippy** [comment]
Hi @SVredeveld, could I pick up this issue?

**Comment by SVredeveld** [comment]
Hi @JaspervdGraaf Go for it!

**Comment by GrillSkippy** [comment]
#16
