### ISSUE TITLE
Add special text for new first placement

### ISSUE THREAD

**Issue by SVredeveld** [SVredeveld/mariobot#8]
When a user submits the fastest time, the /time command only shows the new time. It would be nice if the return text is changed when a new high score is made. 

`NEW FASTEST TIME! @[user] set a new track record with [X:XX:XXX]`

**Comment by SVredeveld** [comment]
Same could be done for second and third placements.

**Comment by CharleneHoogkamer** [comment]
Could you assign me to this issue?

**Comment by SVredeveld** [comment]
@CharleneHoogkamer  go ahead 😄

**Comment by CharleneHoogkamer** [comment]
This issue is solved and can be closed.
